### ISSUE TITLE
Awesome Sign Up Form using HTML CSS with floating labels

### ISSUE THREAD

**Issue by ayushdotdev** [anjali1102/Hacktober2022#215]
Hi @anjali1102 !!
I would like to contribute to your repository by adding awesome Sign up form with floating labels using plain html css 
Please if you could add hackoctober tag or hackoctobertag and please assign this to me .

Thank you !!

**Comment by sufiyanirfan3** [comment]
Assign this issue to me

**Comment by ayushdotdev** [comment]
Hi @sufiyanirfan3 this issue is already assigned to me. 🙂

**Comment by ayushdotdev** [comment]
Thank you !!😀
