### ISSUE TITLE
[up to take]: Tribute page for any social worker HTML CSS, optional JS

### ISSUE THREAD

**Issue by anjali1102** [anjali1102/Hacktober2022#240]
**Is your feature request related to a problem? Please describe.**
- A navbar
- Atleast 1 image 
- A Footer
- Description

**Describe the solution you'd like**

**Comment by Akshaysrajan** [comment]
I Want to do this task can you please assign this task

**Comment by anjali1102** [comment]
u have 3 issues now, if any issue taken on hold for 2 days , will go to other person
