### ISSUE TITLE
[up to take]: make your portfolio website with any tech stack you wish

### ISSUE THREAD

**Issue by anjali1102** [anjali1102/Hacktober2022#243]
**Is your feature request related to a problem? Please describe.**

- make sure to add deployed link

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Akshaysrajan** [comment]
Hello @anjali1102 mam 
can you please assign this task to me. 
I'm a beginner and hope you guide me through this PR.
Thank you

**Comment by Akshaysrajan** [comment]
Deployed Link : https://akshaysrajan.github.io/Hacktober2022/Portfolio/
