### ISSUE TITLE
[up to take]: landing page for your country  HTML,  CSS,  JS optional  

### ISSUE THREAD

**Issue by anjali1102** [anjali1102/Hacktober2022#248]
**Is your feature request related to a problem? Please describe.**

**MAKE SURE TO ADD DEPLOYED LINK ✨✨**
- use your own creativity
- Must have Images
- Navbar, Footer
- Where is your country located, what is special about it, why you love it, cultural , anything u want to share

**Comment by Lo-rraine** [comment]
Hi @anjali1102 

I'd like to add a tribute page for South Africa

**Comment by Rashmi1526** [comment]
Hi @anjali1102 
I would like to add a page for India.

**Comment by intozen** [comment]
Fix issue #369
