### ISSUE TITLE
Landing Page NextJS or  HTML, CSS, use own creativity 

### ISSUE THREAD

**Issue by anjali1102** [anjali1102/Hacktober2022#285]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anjali1102** [comment]
@vishaalupot

**Comment by anjali1102** [comment]
would you like to take this issue ?
i will assign you

**Comment by saivardhankodimela** [comment]
Hey @anjali1102, I would like to take this issue. 
can you assign it?

**Comment by SUBHAMX11** [comment]
i have already built something like this, can you please assign it to me ? I'm sure i would deliver it
