### ISSUE TITLE
[up to take]: Speed typing (typing speed game) HTML, CSS , JS 

### ISSUE THREAD

**Issue by anjali1102** [anjali1102/Hacktober2022#296]
**Is your feature request related to a problem? Please describe.**
With deployed link

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by saivardhankodimela** [comment]
HI @anjali1102, I would like to take this issue.
can you assign it to me?

**Comment by gauriimaheshwarii** [comment]
Hi, can I work on this?

**Comment by anjali1102** [comment]
@gauriimaheshwarii already assigned,  you can take other issues
