### ISSUE TITLE
[Up to take]: ReactJS project with Hooks

### ISSUE THREAD

**Issue by anjali1102** [anjali1102/Hacktober2022#539]
**Is your feature request related to a problem? Please describe.**

**Deployed link**

USE YOUR OWN CREATIVITY

**Comment by Jorge-Neves** [comment]
Greetings I would like to apply to solve this open issue:

https://github.com/anjali1102/Hacktober2022/pull/570

My proposed solution is a React Typescript PWA that works both offline and online (and on all OS systems that support chrome, like IOS, android, etc) that users could use to virtually toss coins. My solution in particular makes use of the following react hooks:

useState;
useEffect.

Thank you for your time
