### ISSUE TITLE
Remove vertical scrolling

### ISSUE THREAD

**Issue by anjali1102** [anjali1102/Hacktober2022#7]
**Describe the bug**

In this  [Project](https://github.com/anjali1102/Hacktober2021/tree/master/CSS3_SVG_Animation) , remove the vertical scrolling bar.

You can play with Sizing, without hampering the core of project.

And then add your project screenshot in [here](https://github.com/anjali1102/Hacktober2021/blob/master/README.md)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Swapnil-Gaur** [comment]
please review the pull request
